// primeira-single-page-react/src/components/Resumo/Resumo.js
import React, { Component } from "react";
import { consultarResumo } from "../../services/resumo";

class Resumo extends Component {

    constructor(props) {
        super(props);
        this.state = {
            consultas: {
                consultas_30dias_anteiores: 0,
                consultas_30dias_posteriores: 0
            },
            faturamento: {
                anterior: {
                    valor: 0,
                    comparativo: 0
                },
                previsao: {
                    valor: 0,
                    comparativo: 0
                }
            }
        }
    }

    componentDidMount() {                
        consultarResumo(dados => this.setState(dados));
    }

    render() {
        return (
            <div>
                <h2 className="mt-2">Resumo</h2>

                <div className="row">
                    <div className="col">
                        <h3>Consultas</h3>

                        <div className="row">
                            <div className="col">
                                <div className="card mt-2 text-center">
                                    <div className="card-header">
                                        30 dias anteriores
                                    </div>
                                    <div className="card-body">
                                        {this.state.consultas.consultas_30dias_anteiores}
                                    </div>
                                </div>
                            </div>
                            <div className="col">
                                <div className="card mt-2 text-center">
                                    <div className="card-header">
                                        Próximos 30 dias
                                    </div>
                                    <div className="card-body">
                                        {this.state.consultas.consultas_30dias_posteriores}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col">
                        <h3>Faturamento</h3>

                        <div className="row">
                            <div className="col">
                                <div className="card mt-2 text-center">
                                    <div className="card-header">
                                        30 dias anteriores
                                    </div>
                                    <div className="card-body">
                                        {this.state.faturamento.anterior.valor.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}
                                        <span className={"badge ml-1 " + (this.state.faturamento.anterior.comparativo > 0 ? "badge-success" : "badge-danger")}>
                                            {this.state.faturamento.anterior.comparativo} %
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div className="col">
                                <div className="card mt-2 text-center">
                                    <div className="card-header">
                                        Próximos 30 dias
                                    </div>
                                    <div className="card-body">
                                        {this.state.faturamento.previsao.valor.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}
                                        <span className={"badge ml-1 " + (this.state.faturamento.previsao.comparativo > 0 ? "badge-success" : "badge-danger")}>
                                            {this.state.faturamento.previsao.comparativo} %
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }    
}

export default Resumo;

// primeira-single-page-angular/treinamento-angular/src/app/resumo/resumo.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ResumoService } from './resumo.service';


@Component({
  selector: 'app-resumo',
  templateUrl: './resumo.component.html',
  styleUrls: ['./resumo.component.css']
})
export class ResumoComponent implements OnInit, OnDestroy {

  resumo;
  inscricao;

  constructor(private resumoService: ResumoService) { }

  ngOnInit() {
    this.inscricao = this.resumoService.getResumo()
      .subscribe(dados => this.resumo = dados);
  }

  ngOnDestroy() {
    this.inscricao.unsubscribe();
  }

}
<div *ngIf="resumo">
  <app-painel-simples titulo="Consultas Marcadas Últimos 30 dias" col="6">
    <h3 class="text-center">{{resumo.consultas.consultas_30dias_anteiores}}</h3>
  </app-painel-simples>

  <app-painel-simples titulo="Consultas Marcadas Próximos 30 dias" col="6">
    <h3 class="text-center">{{resumo.consultas.consultas_30dias_posteriores}}</h3>
  </app-painel-simples>

  <app-painel-simples col="6" titulo="Faturamento Anterior">
    <div class="box-faturamento">
      <div class="col-md-10">
        <h1 class="text-left">{{resumo.faturamento.anterior.valor | currency:'BRL'}}</h1>
      </div>
      <div class="alert col-md-2 sm"
        [ngClass]="resumo.faturamento.anterior.comparativo >= 0 ? 'alert-success' : 'alert-danger' ">
        <b>{{resumo.faturamento.anterior.comparativo}}%</b>
      </div>
    </div>
  </app-painel-simples>

  <app-painel-simples col="6" titulo="Faturamento Previsão">
    <div class="box-faturamento">
      <div class="col-md-10">
        <h1 class="text-left">{{resumo.faturamento.previsao.valor | currency:'BRL'}}</h1>
      </div>
      <div class="alert col-md-2 sm"
        [ngClass]="resumo.faturamento.previsao.comparativo >= 0 ? 'alert-success' : 'alert-danger' ">
        <b>{{resumo.faturamento.previsao.comparativo}}%</b>
      </div>
    </div>
  </app-painel-simples>
</div>
